name = "eson"          # Worker 名称（自定义）
main = "worker.js"     # 入口文件（必须与实际文件名一致）
type = "worker"         # 关键！声明为 Worker 类型（非静态站点）
#compatibility_date = "2025-06-13"  # 建议保留

[secrets]              # Workers 加密变量（若需要）
UUID = "UUID"   # 变量名需与代码一致
TROJAN_PASSWORD = "TR_PASS"
