name = "eson"          # Worker 名称
main = "worker.js"     # 入口文件
compatibility_date = "2025-06-13"  # 必填，建议使用当前日期

# 移除以下字段（若通过 GitHub Actions 传递机密，无需本地声明）
# type = "worker"
# [secrets]
# UUID = "UUID"
# TROJAN_PASSWORD = "TR_PASS"
