jobs:
  deploy-env1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cloudflare/wrangler-action@3.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_TOKEN_ENV1 }}
          workers: worker.js
          env: |
            UUID=${{ secrets.UUID_ENV1 }}

  deploy-env2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cloudflare/wrangler-action@3.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_TOKEN_ENV2 }}
          workers: worker.js
          env: |
            UUID=${{ secrets.UUID_ENV2 }}
