name: Deploy Cloudflare Worker
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      comment:
        description: 'Manual deployment comment'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Wrangler CLI
        run: npm install -g wrangler@4.20.0  # 固定版本，匹配兼容性

      - name: Deploy to Cloudflare Workers
        run: wrangler deploy --no-telemetry  # 改用 deploy 命令，更适合纯 Worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          # 可选：若需指定账户 ID（自动获取时可省略）
          # CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
